### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by stevedesmond-ca** [stevedesmond-ca/ImageResizer#4]
Do my laundry!

**Comment by pcblues** [comment]
I tried to build this on Windows 10 with VS2015 Enterprise but received this error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1002	The dependency ImageProcessorCore 1.0.0-alpha1095 in project ImageResizer2 does not support framework DNX,Version=v4.5.1.	ImageResizer	C:\Users\mo\Source\Repos\ImageResizer2\project.json	6	
> 

Any ideas? I was thinking of creating some tests.

**Comment by stevedesmond-ca** [comment]
Do you have .NET Core 1.1 and the Preview 2 VS tooling installed?

**Comment by pcblues** [comment]
Thanks. It must have tried to work with 4.5.1 in the absence of dotnetcore. I'm a bit new to github and this tech so feel free to slap me around :)

**Comment by pcblues** [comment]
With respect to unit testing, were you thinking of using something like [xUnit](http://xunit.github.io/docs/getting-started-dotnet-core)?

**Comment by stevedesmond-ca** [comment]
Yes, xunit please

**Comment by stevedesmond-ca** [comment]
A test project and simple test has been added.

TODO: (personal reminders, not expecting @pcblues to pick this up)
- make Resizer non-static, break out methods into more testable units
- ImageSharp and file system commands should be extracted to injected services for mockability
- break testable items out of Program so they can be tested

**Comment by bradleyas** [comment]
Why do you need to make it non static? You'd have to instantiate a Resizer Object. is that what you want?

**Comment by stevedesmond-ca** [comment]
Yeah, see the 2nd bullet point, to allow mocking through constructor arg DI.

**Comment by stevedesmond-ca** [comment]
Sufficient coverage has been added for now
