### ISSUE TITLE
Add build prerequisites for VS2015 to README

### ISSUE THREAD

**Issue by pcblues** [stevedesmond-ca/ImageResizer#9]
Hi there.

In order to feel my way around, I cloned the project, opened in VS2015 and added prerequisites to the README.md file in a new local branch.
I got a 403 error when trying to Create a pull request from pcblues to master.
Should I be forking it instead, do you need to give me permission to create a pull request, or is there something else I should be doing?

Thanks.

**Comment by stevedesmond-ca** [comment]
Yeah, you'll need to fork the repo, clone that (or add it as a remote) push your changes to your copy, and then initiate a PR (I think from either repo) on GitHub.

**Comment by pcblues** [comment]
Thanks.
